### ISSUE TITLE
Make typed text not input moves 

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#139]
Right now, if you have a heister selected with 1,2,3,4, and you enter the chat box and start typing any message that contains any letters that might send a move, a move will be sent.

Lifehack: make selecting the chat box (focus? is that the term?) remove heister selection

**Comment by banool** [comment]
I can make it that if the chat box is active, it sets some state, which we then check when receiving key input at the document level.

**Comment by banool** [comment]
Fixed with https://github.com/banool/team_heist_tactics/commit/a4bf8c8506e4a65b1fd10570419f2726febc3639.
