### ISSUE TITLE
Implement "card flip"

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#142]
Game state should keep track of this stuff, and it should affect how moves are handled  - eg. teleports disallowed, map escapes allowed.

You can only flip this card when ALL heisters are on their item spaces, AND the card hasn't been flipped yet.
AKA, this is something that you probably have to constantly check whether they're on their matching item spaces.

**Comment by banool** [comment]
You can use the `all_items_taken` for this, so there is something in the GameState at least already.
