### ISSUE TITLE
Implement "escape"

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#145]
as either a new message type or a move of some sort.

My current vote is for "F" for "flee"

**Comment by banool** [comment]
I figure this can be handled entirely on the server side. If the player moves a heister to an escape tile and all items have been picked up, they escape.

**Comment by kemcbride** [comment]
it is automatic

**Comment by kemcbride** [comment]
wait uhh why did i comment that. i mean, I'm doing a PR where escapes happen automatically.
