### ISSUE TITLE
Implement "taps"

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#147]

**Comment by kemcbride** [comment]
tbh idk how we're going to do this yet. it'd be really convenient if it was completely via the UI, but i think it'd be cooler and more neato if it was done between both server & frontend

**Comment by banool** [comment]
How would you do it completely via the UI?

**Comment by kemcbride** [comment]
uhhhhhhhhhh......... ... ... ..... .... .... .... I don't know actually lol you're right. i guess they don't have websockets to each other.

**Comment by banool** [comment]
- https://github.com/banool/team_heist_tactics/commit/4418329d3c2d7dc0d773e247a00c54405a4f10f7 
- https://github.com/banool/team_heist_tactics/commit/55d2c47e38aac1f1ae950d2c30ce354f340632ac
