### ISSUE TITLE
Fix actions to properly run if a diff includes both ui & server changes :(

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#163]
I thought I was being pretty clever splitting them up... saving those CPU cycles if your changes only affect one part of the build. But I was not clever! Now it doesn't run _any_ actions if your diff affects both ui & server, which makes it pretty dang moot!

**Comment by banool** [comment]
Should be fixed in https://github.com/banool/team_heist_tactics/commit/2f7d0f919f54d37942ed902f0c603c07fdc0fb33.

**Comment by banool** [comment]
Okay and also these, ya really did a number on this file I didn't notice all the changes:
- https://github.com/banool/team_heist_tactics/commit/03c7b8d16806ac4b74d9e9f963e24ae35bb7c030
- https://github.com/banool/team_heist_tactics/commit/96001e1d5064497662970d8fc906134c5e04f0e8

**Comment by banool** [comment]
The previous changes stopped the build from running if not all of the previous steps ran. I have fixed this in https://github.com/banool/team_heist_tactics/issues/163.
