### ISSUE TITLE
Make server return list of valid map positions for placing new tile

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#22]
This could just get calculated every time the webserver part of the server calls `get_game_state()`.

**Comment by kemcbride** [comment]
Do we want these to be what they currently are? Which is like

```
  _   _
| z |   |
  _   _
|   |   |
  _   _
|   |   |
  _   _
|   |   | y |
  _   _   =
|   |   | x |
  _   _
|   |   |
```

y is new tile request location, if x is player x with door =  and new tile corner is z

**Comment by kemcbride** [comment]
Like we could make the request take z and a rotation or something.

**Comment by kemcbride** [comment]
Just gonna add it to the game state.

**Comment by kemcbride** [comment]
note: we are going with location y even still, it's all good

**Comment by kemcbride** [comment]
Ungh Still wrong - mismatched colors can pass. What's up with that?!
