### ISSUE TITLE
Think of solution for drag and drop between squares that don't fit within the canvas viewport

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#34]
One way to do this would be to lock the cursor in the canvas and then implement edge map panning, but that's getting pretty tricky. Another would be perhaps to implement zoom, or a button that toggles a view where the whole map fits in the canvas.

**Comment by fboxwala** [comment]
I think that zoom is actually a really intuitive way to implement it. I keep trying to zoom in and out with my mouse scroll.

**Comment by kemcbride** [comment]
Zoom implemented: 61ebbe0eb869a31d48b7d7d5d792a02a9ae116da
