### ISSUE TITLE
TilePlacement - disallow TilePlacement beyond doors that already have a tile placed

### ISSUE THREAD

**Issue by kemcbride** [banool/team_heist_tactics#49]
I got into a funky situation where I drew a tile on top of another tile.

What is the expected behavior?
The expected behavior is to disallow that kind of placement.

**Comment by kemcbride** [comment]
This and #60  can both be fixed by "Opening doors" on newly-drawn tiles that are adjacent to already-existing doors.

It is necessary to open both doors in those cases.
Should be totally doable.

**Comment by banool** [comment]
Massive brain.
