### ISSUE TITLE
Allow multiple moves in a row in the same direction

### ISSUE THREAD

**Issue by banool** [banool/team_heist_tactics#97]
This could probably be just a server side thing.

**Comment by kemcbride** [comment]
this is what im thinking:

you get a move, and if it doesn't fall into any of the normal categories (adjacent, escalator, teleport) then we ask:
* are you moving in one single cardinal direction?
* if so, are there any walls between you and your destination that would render that move invalid?

so, not too terrible, but potentially weird with many walls. eg. also if there's a single gap in teh grid, that's also bad (but similarly can be handled easily)
